name: test

on: 
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update and install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y file curl git vim tmux gcc make

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Download install script
        run: curl -fsSL https://raw.githubusercontent.com/rht27/dotfiles/main/install.sh

      - name: Install dotfiles
        run: sh install_linux.sh
